### PR TITLE
Only one instance of the bus is available. 

### PR DESCRIPTION
**Pull request by ibiBgOR**
Even if Singletons are bad, it's perfect for an event bus. No one have to pass the bus as an param with the constructor.

### CODE REVIEW

**Comment by heynemann** [comment]
What if I need two different event buses (say one for each thread)? The way you implemented it, there's no way to do it.

If a singleton makes sense, then I'd rather have something in the same line of tornado's event loop singleton:

```
ioloop.instance() # => always returns the same instance
# but if you create a new ioloop, it's actually a new one:
my_loop = ioloop()
```

What do you think?

**Comment by ibiBgOR** [comment]
What if there would be an map/dictionary of instances. Then there would only be the need of two or three additional methods:
    `def getOrCreate(name) - Generates a new Instance if there is none within the dictionary with the given name and returns it`
    `def get(name) - returns the bus with the given name. If no bus was found then None is returned
`def destroy(name) - destroys the eventbus with the given name or does nothing if no eventbus instance got the name.`

The only problem i got is that i cannot simply write my **init** without thinking on the bus as param. And if I want to add eventbus compatibility with my project I have to change more or less much code. But if there would only be one, or there would be getter to get a specific bus (maybe with an fourth method `def get()` which only returns the base / first eventbus), with this I could easily add cyrusbus to any project without making to much changes.

I hope you get my point?!
Greets :)

**Comment by ibiBgOR** [comment]
Hey there,
its been a while since my last action on this project. I got mass of work to do. But I took some time and made these changes. I implemented the methods I wrote. It is now possible to just create a bus instance and use cyrusbus the way it worked before, but it is also possible to use cyrusbus with just one bus instance and get this instance more easier than before.
I added some static methods to the bus. You can simply get a bus by calling get_or_create(<name>) and there would be an instance of the bus with the given name.

Oh and I added some "Python-Doc" and descriptions in the code.

Merry Christmas :)

**Comment by heynemann** [comment]
Awesome!!! Good JOB!

**Pull request merged**
